### ISSUE TITLE
Looks good, but missing one part

### ISSUE THREAD

**Issue by ohaddahan** [dongri/bounty-001#1]
The request was to set the value via extension, and fetch the same value from leveldb via the script.

Not write/read inside leveldb or extension, the aim is cross application access.

**Comment by ohaddahan** [comment]
@dongri

**Comment by ohaddahan** [comment]
Steps should be:
1. `chrome.storage.set`.
2. In script , fetch the value from step 1.

**Comment by dongri** [comment]
@ohaddahan 
I misunderstood. I'm sorry.

1. Specified the value for the key in the Chrome extension.
2. Retrieved the value for the key in Rust.

Implemented in the latest main branch.
